FROM python:latest

RUN apt -y install git

RUN apt update -y

RUN apt upgrade -y

RUN apt -y install python3-pip

RUN python3 -m pip install --upgrade pip

RUN git clone https://github.com/bmol5/Finance-Full-Stack-Web-App-using-Flask-and-SQL.git FinanceApp

WORKDIR /FinanceApp

RUN echo "API_KEY=$$ENTER_YOUR_KEY$$" > .env

RUN pip install -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=application

ENTRYPOINT flask run --host=0.0.0.0 -p 5000
