FROM python:latest

RUN apt -y install git

RUN apt update -y

RUN apt upgrade -y

RUN apt -y install python3-pip

RUN python3 -m pip install --upgrade pip

RUN git clone -b cypress-testing https://github.com/herimendoza/Finance-Full-Stack-Web-App-using-Flask-and-SQL.git FinanceApp

WORKDIR /FinanceApp

RUN echo "API_KEY=795fbe077cmsh5bf4c19961cc93dp1668a3jsn0e9080cd4081" > .env

RUN pip install -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=application

ENTRYPOINT flask run --host=0.0.0.0 -p 5000
